version: "ALPHA 0.0.1"

# API UI YE POST OLARAK ATACAK

#------------[ SERVER ]------------#
server:
  host         : "localhost"
  port         : 9876
  idletimeout  : 120
  readtimeout  : 1
  writetimeout : 1
  checktimeout : 60

#------------[ CORS ]---------------#
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://example.com"

  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"

  allowed_headers:
    - "Content-Type"
    - "Authorization"

#-----------[ SERVICES ]------------#
services:
  mysql:
    db_host      : "localhost"
    db_port      : 3306
    db_user      : "db_user"
    db_pass      : "db_password"
    db_net       : "tcp"
    db_root_pass : "rootpass"
    db_name      : "LIBRARY"
    db_srvname   : "mysql"

  postgres:
    db_host    : "localhost"
    db_port    : 5432
    db_user    : "postgres"
    db_pass    : "password"
    db_name    : "postgres"
    db_timeout : 5
    db_srvname : "postgres"
    db_sslmode : "disable"

  postgres2:
      db_host    : "localhost"
      db_port    : 5432
      db_user    : "postgres"
      db_pass    : "changeme"
      db_name    : "postgres"
      db_timeout : 5
      db_srvname : "postgres"
      db_sslmode : "disable"
